export const state = () => ({
  questions: [
    {
      slug: 'pregunta_a',
      text: '¿De quién se habla en el texto?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_1.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué fue lo primero que hizo Juan, al despertarse el primer día de clases?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_2.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué pasó luego de despedirse de sus padres?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_3.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_d',
      text: '¿Qúe lugar visitó Juan durante sus vacaciones?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_4.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_e',
      text: '¿Qúe significa la palabra piscicultura?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_4.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_f',
      text: '¿Qúe sucedió al final con Juan?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_4.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_a',
      text: '¿Con quién trabajaba en el circo el payaso Pirulín?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_2/pregunta_1.jpg',
      parent: 'lectura_2',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué le sucedió a Piruetita juguetón?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_2/pregunta_2.jpg',
      parent:'lectura_2',
    },
    {
      slug: 'pregunta_c',
      text: '¿Cuál es el mensaje que nos deja la presente lectura?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_2/pregunta_3.jpg',
      parent:'lectura_2',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué trata el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_3/pregunta_1.jpg',
      parent:'lectura_3',
    },
    {
      slug: 'pregunta_b',
      text: '¿Para que se ha escrito el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_3/pregunta_2.jpg',
      parent:'lectura_3',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué tipo de texto es?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_3/pregunta_3.jpg',
      parent:'lectura_3',
    },
    {
      slug: 'pregunta_d',
      text: '¿Por qué se les rinde un homenaje a los maestros en su día?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_3/pregunta_4.jpg',
      parent:'lectura_3',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué trata el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_4/pregunta_1.jpg',
      parent:'lectura_4',
    },
    {
      slug: 'pregunta_b',
      text: '¿Por qué está orgullosa de su país llamado Perú?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_4/pregunta_2.jpg',
      parent:'lectura_4',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué tipo de melodía tiene la canción?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_4/pregunta_3.jpg',
      parent:'lectura_4',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué debes hacer primero para ser buen peatón?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_5/pregunta_1.png',
      parent:'lectura_5',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué debes hacer luego de reconocer las señales de tránsito?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_5/pregunta_2.png',
      parent:'lectura_5',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué debes hacer <span style="text-decoration: underlying">finalmente<spam>?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_5/pregunta_3.png',
      parent:'lectura_5',
    },
    {
      slug: 'pregunta_d',
      text: '¿Para qué debes seguir las recomendaciones de Zoila?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_5/pregunta_4.png',
      parent:'lectura_5',
    },
    {
      slug: 'pregunta_e',
      text: '¿Para qué se escribió este texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_5/pregunta_5.png',
      parent:'lectura_5',
    },
    {
      slug: 'pregunta_a',
      text: '¿Con quienes va Fabian al parque a sembrar árboles?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_6/pregunta_1.jpg',
      parent:'lectura_6',
    },
    {
      slug: 'pregunta_b',
      text: '¿Con qué propósito Fabian va a sembrar más árboles en el parque?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_6/pregunta_2.jpg',
      parent:'lectura_6',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué te parece la acción de Fabian?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_6/pregunta_3.jpg',
      parent:'lectura_6',
    },
    {
      slug: 'pregunta_a',
      text: '¿De quíenes se habla en el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_7/pregunta_1.jpg',
      parent:'lectura_7',
    },
    {
      slug: 'pregunta_b',
      text: '¿Para quíenes Justino realizó un gran concierto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_7/pregunta_2.jpg',
      parent:'lectura_7',
    },
    {
      slug: 'pregunta_c',
      text: '¿Por qué Justino realizó un gran concierto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_7/pregunta_3.jpg',
      parent:'lectura_7',
    },
    {
      slug: 'pregunta_d',
      text: '¿Qué pasó al final del texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_7/pregunta_4.jpg',
      parent:'lectura_7',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué texto has leído?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_8/pregunta_1.jpg',
      parent:'lectura_8',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué ha pasado con el niño?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_8/pregunta_2.jpg',
      parent:'lectura_8',
    },
    {
      slug: 'pregunta_c',
      text: '¿Por qué se dice que es ejemplo de perseverancia?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_8/pregunta_3.jpg',
      parent:'lectura_8',
    },
    {
      slug: 'pregunta_d',
      text: '¿Cuál es el sueño del niño?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_8/pregunta_3.jpg',
      parent:'lectura_8',
    },
    {
      slug: 'pregunta_a',
      text: '¿Quién era la protagonista principal del cuento?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_9/pregunta_1.jpg',
      parent:'lectura_9',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué dificultades tenía la liebre?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_9/pregunta_1.jpg',
      parent:'lectura_9',
    },
    {
      slug: 'pregunta_c',
      text: '¿Por qué se corrían los animales del bosque?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_9/pregunta_1.jpg',
      parent:'lectura_9',
    },
    {
      slug: 'pregunta_d',
      text: '¿Qué hacía la liebre mientras huían?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_9/pregunta_1.jpg',
      parent:'lectura_9',
    },
    {
      slug: 'pregunta_e',
      text: '¿Lograron cazarla?, ¿por qué?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_9/pregunta_1.jpg',
      parent:'lectura_9',
    },
    {
      slug: 'pregunta_f',
      text: '¿Qué nos enseña el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_9/pregunta_1.jpg',
      parent:'lectura_9',
    },
    {
      slug: 'pregunta_a',
      text: '¿De quién se habla en el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_10/pregunta_1.jpg',
      parent:'lectura_10',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué pasaba con el pueblo de Rita?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_10/pregunta_1.jpg',
      parent:'lectura_10',
    },
    {
      slug: 'pregunta_c',
      text: '¿Cómo se sintieron cuando llegó la energía eléctrica?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_10/pregunta_3.jpg',
      parent:'lectura_10',
    },
    {
      slug: 'pregunta_d',
      text: '¿Qué hacía Rita cuanto tuvieron luz?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_10/pregunta_4.jpg',
      parent:'lectura_10',
    },
    {
      slug: 'pregunta_e',
      text: '¿Cómo se sintieron cuando se fue la Energía?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_10/pregunta_3.jpg',
      parent:'lectura_10',
    },
    {
      slug: 'pregunta_a',
      text: '¿De quiénes se habla en el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_11/pregunta_1.jpg',
      parent:'lectura_11',
    },
    {
      slug: 'pregunta_b',
      text: '¿En dónde sucedieron los hechos?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_11/pregunta_1.jpg',
      parent:'lectura_11',
    },
    {
      slug: 'pregunta_c',
      text: '¿Cómo comienza la anécdota?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_11/pregunta_1.jpg',
      parent:'lectura_11',
    },
    {
      slug: 'pregunta_d',
      text: '¿Por qué las personas oraban por el Cristo de Pachacamilla?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_11/pregunta_1.jpg',
      parent:'lectura_11',
    },
    {
      slug: 'pregunta_e',
      text: '¿Qué aprendió de su abuelita?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_11/pregunta_1.jpg',
      parent:'lectura_11',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué observas en la imagen?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_1/pregunta_1.jpg',
      parent:'juego_1',
    },
    {
      slug: 'pregunta_b',
      text: '¿De qué crees que tratará el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_1/pregunta_1.jpg',
      parent:'juego_1',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué tipo de texto será?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_1/pregunta_1.jpg',
      parent:'juego_1',
    },
    {
      slug: 'pregunta_a',
      text: '¿Cuál sería el mejor título para el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_2/pregunta_1.jpg',
      parent:'juego_2',
    },
    {
      slug: 'pregunta_b',
      text: '¿De qué crees que tratará el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_2/pregunta_1.jpg',
      parent:'juego_2',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué crees que tratará el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_4/pregunta_1.jpg',
      parent:'juego_4',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué crees que tratará el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_5/pregunta_1.jpg',
      parent:'juego_5',
    },
    {
      slug: 'pregunta_a',
      text: '¿Cuál será el título del texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_6/pregunta_1.jpg',
      parent:'juego_6',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué crees que tratará el texto?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_7/pregunta_1.jpg',
      parent:'juego_7',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué está haciendo el niño?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_8/pregunta_1.jpg',
      parent:'juego_8',
    },
    {
      slug: 'pregunta_b',
      text: '¿Por qué crees que estará escribiendo en la calle y de noche?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_8/pregunta_1.jpg',
      parent:'juego_8',
    },
    {
      slug: 'pregunta_a',
      text: '¿De quién es la imagen?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_9/pregunta_1.jpg',
      parent:'juego_9',
    },
    {
      slug: 'pregunta_b',
      text: '¿Cuáles son sus características?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_9/pregunta_1.jpg',
      parent:'juego_9',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué objetos relacionaste?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_10/pregunta_1.jpg',
      parent:'juego_10',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué necesitan estos electrodomésticos para funcionar?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_10/pregunta_1.jpg',
      parent:'juego_10',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué frase formaste en el rompecabezas?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_11/pregunta_1.jpg',
      parent:'juego_11',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué observas en la imagen?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_11/pregunta_1.jpg',
      parent:'juego_11',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué conoces sobre el Señor de los Milagros?',
      body:'',
      hint:'',
      type:'multiple choice',
      image:'lectura_11/pregunta_1.jpg',
      parent:'juego_11',
    },
  ],
})

export const getters = {
  getQuestionsByParent: state => id => {
    if (!id) return []
    return state.questions.filter(question => {
      return question.parent === id
    })
  },
}

export const mutations = {
  toggle(state, todo) {
    todo.done = !todo.done
  },
}
