export const state = () => ({
  questions: [
    {
      slug: 'pregunta_a',
      text: '¿De quién se habla en el texto?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_1.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué fue lo primero que hizo Juan, al despertarse el primer día de clases?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_2.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué pasó luego de despedirse de sus padres?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_3.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_d',
      text: '¿Qúe lugar visitó Juan durante sus vacaciones?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_4.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_e',
      text: '¿Qúe significa la palabra piscicultura?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_4.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_f',
      text: '¿Qúe sucedió al final con Juan?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_1/pregunta_4.jpg',
      parent: 'lectura_1',
    },
    {
      slug: 'pregunta_a',
      text: '¿Con quién trabajaba en el circo el payaso Pirulín?',
      body: '',
      hint: '',
      type: 'multiple_choice',
      image: 'lectura_2/pregunta_1.jpg',
      parent: 'lectura_2',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué le sucedió a Piruetita juguetón?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_2/pregunta_2.jpg',
      parent: 'lectura_2',
    },
    {
      slug: 'pregunta_c',
      text: '¿Cuál es el mensaje que nos deja la presente lectura?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_2/pregunta_3.jpg',
      parent: 'lectura_2',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué trata el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_3/pregunta_1.jpg',
      parent: 'lectura_3',
    },
    {
      slug: 'pregunta_b',
      text: '¿Para que se ha escrito el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_3/pregunta_2.jpg',
      parent: 'lectura_3',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué tipo de texto es?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_3/pregunta_3.jpg',
      parent: 'lectura_3',
    },
    {
      slug: 'pregunta_d',
      text: '¿Por qué se les rinde un homenaje a los maestros en su día?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_3/pregunta_4.jpg',
      parent: 'lectura_3',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué trata el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_4/pregunta_1.jpg',
      parent: 'lectura_4',
    },
    {
      slug: 'pregunta_b',
      text: '¿Por qué está orgullosa de su país llamado Perú?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_4/pregunta_2.jpg',
      parent: 'lectura_4',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué tipo de melodía tiene la canción?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_4/pregunta_3.jpg',
      parent: 'lectura_4',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué batalla se trata en el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_5/pregunta_1.jpg',
      parent: 'lectura_5',
    },
    {
      slug: 'pregunta_b',
      text: '¿Por qué luchaban los patriotas?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_5/pregunta_2.jpg',
      parent: 'lectura_5',
    },
    {
      slug: 'pregunta_c',
      text: '¿En la lectura quiénes son los héroes en la Batalla de Junín?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_5/pregunta_3.jpg',
      parent: 'lectura_5',
    },
    {
      slug: 'pregunta_d',
      text: 'Finalmente, ¿Quiénes ayudaron en la victoria del Perú?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_5/pregunta_4.jpg',
      parent: 'lectura_5',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué trata el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_6/pregunta_1.jpg',
      parent: 'lectura_6',
    },
    {
      slug: 'pregunta_b',
      text: ' ¿Quiénes son los personajes en el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_6/pregunta_2.jpg',
      parent: 'lectura_6',
    },
    {
      slug: 'pregunta_c',
      text: '¿Cuál era el problema entre Jací y Guarací? ',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_6/pregunta_3.jpg',
      parent: 'lectura_6',
    },
    {
      slug: 'pregunta_d',
      text: 'Finalmente, ¿Qué pasó con Jací y Guarací?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_6/pregunta_4.jpg',
      parent: 'lectura_6',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué se trata la lectura?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_7/pregunta_1.jpg',
      parent: 'lectura_7',
    },
    {
      slug: 'pregunta_b',
      text: '¿De qué danza se habla en el texto? ',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_7/pregunta_2.jpg',
      parent: 'lectura_7',
    },
    {
      slug: 'pregunta_c',
      text: '¿En qué se parecen La Marinera y el Huayno?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_7/pregunta_3.jpg',
      parent: 'lectura_7',
    },
    {
      slug: 'pregunta_d',
      text: '¿Qué se demuestra en la Danza de la Boa? ',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_7/pregunta_4.jpg',
      parent: 'lectura_7',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué texto has leido?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_8/pregunta_1.png',
      parent: 'lectura_8',
    },
    {
      slug: 'pregunta_b',
      text: '¿Para quién se ha escrito la carta?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_8/pregunta_2.png',
      parent: 'lectura_8',
    },
    {
      slug: 'pregunta_c',
      text: ' ¿Para qué se ha escrito el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_8/pregunta_3.png',
      parent: 'lectura_8',
    },
    {
      slug: 'pregunta_d',
      text: '¿Quién a escrito el texto? ',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_8/pregunta_4.png',
      parent: 'lectura_8',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué debes hacer primero para ser buen peatón?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_9/pregunta_1.png',
      parent: 'lectura_9',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué debes hacer luego de reconocer las señales de tránsito?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_9/pregunta_2.png',
      parent: 'lectura_9',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué debes hacer <span style="text-decoration: underlying">finalmente<spam>?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_9/pregunta_3.png',
      parent: 'lectura_9',
    },
    {
      slug: 'pregunta_d',
      text: '¿Para qué debes seguir las recomendaciones de Zoila?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_9/pregunta_4.png',
      parent: 'lectura_9',
    },
    {
      slug: 'pregunta_e',
      text: '¿Para qué se escribió este texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_9/pregunta_5.png',
      parent: 'lectura_9',
    },
    {
      slug: 'pregunta_a',
      text: '¿Con quienes va Fabian al parque a sembrar árboles?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_10/pregunta_1.jpg',
      parent: 'lectura_10',
    },
    {
      slug: 'pregunta_b',
      text: '¿Con qué propósito Fabian va a sembrar más árboles en el parque?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_10/pregunta_2.jpg',
      parent: 'lectura_10',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué te parece la acción de Fabian?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_10/pregunta_3.jpg',
      parent: 'lectura_10',
    },
    {
      slug: 'pregunta_a',
      text: '¿De quíenes se habla en el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_10/pregunta_1.jpg',
      parent: 'lectura_11',
    },
    {
      slug: 'pregunta_b',
      text: '¿Para quíenes Justino realizó un gran concierto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_11/pregunta_2.jpg',
      parent: 'lectura_11',
    },
    {
      slug: 'pregunta_c',
      text: '¿Por qué Justino realizó un gran concierto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_11/pregunta_3.jpg',
      parent: 'lectura_11',
    },
    {
      slug: 'pregunta_d',
      text: '¿Qué pasó al final del texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_11/pregunta_4.jpg',
      parent: 'lectura_11',
    },
    {
      slug: 'pregunta_a',
      text: '¿Dónde ocurrieron los hechos?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_12/pregunta_1.jpg',
      parent: 'lectura_12',
    },
    {
      slug: 'pregunta_b',
      text: '¿Por qué Juanita les invita a jugar en el bosque a sus amigos?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_12/pregunta_2.jpg',
      parent: 'lectura_12',
    },
    {
      slug: 'pregunta_c',
      text: '.¿Qué opinas sobre las conductas de Jorge y Jana?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_12/pregunta_3.jpg',
      parent: 'lectura_12',
    },
    {
      slug: 'pregunta_a',
      text: '¿Quién era la protagonista principal del cuento?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_13/pregunta_1.jpg',
      parent: 'lectura_13',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué dificultades tenía la liebre?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_13/pregunta_1.jpg',
      parent: 'lectura_13',
    },
    {
      slug: 'pregunta_c',
      text: '¿Por qué se corrían los animales del bosque?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_13/pregunta_1.jpg',
      parent: 'lectura_13',
    },
    {
      slug: 'pregunta_d',
      text: '¿Qué hacía la liebre mientras huían?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_13/pregunta_1.jpg',
      parent: 'lectura_13',
    },
    {
      slug: 'pregunta_e',
      text: '¿Lograron cazarla?, ¿por qué?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_13/pregunta_1.jpg',
      parent: 'lectura_13',
    },
    {
      slug: 'pregunta_f',
      text: '¿Qué nos enseña el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_13/pregunta_1.jpg',
      parent: 'lectura_13',
    },
    {
      slug: 'pregunta_a',
      text: '¿De quién se habla en el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_14/pregunta_1.jpg',
      parent: 'lectura_14',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué pasaba con el pueblo de Rita?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_14/pregunta_1.jpg',
      parent: 'lectura_14',
    },
    {
      slug: 'pregunta_c',
      text: '¿Cómo se sintieron cuando llegó la energía eléctrica?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_14/pregunta_3.jpg',
      parent: 'lectura_14',
    },
    {
      slug: 'pregunta_d',
      text: '¿Qué hacía Rita cuanto tuvieron luz?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_14/pregunta_4.jpg',
      parent: 'lectura_14',
    },
    {
      slug: 'pregunta_e',
      text: '¿Cómo se sintieron cuando se fue la Energía?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_14/pregunta_3.jpg',
      parent: 'lectura_14',
    },
    {
      slug: 'pregunta_a',
      text: '¿De quiénes se habla en el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_15/pregunta_1.jpg',
      parent: 'lectura_15',
    },
    {
      slug: 'pregunta_b',
      text: '¿En dónde sucedieron los hechos?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_15/pregunta_1.jpg',
      parent: 'lectura_15',
    },
    {
      slug: 'pregunta_c',
      text: '¿Cómo comienza la anécdota?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_15/pregunta_1.jpg',
      parent: 'lectura_15',
    },
    {
      slug: 'pregunta_d',
      text: '¿Por qué las personas oraban por el Cristo de Pachacamilla?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_15/pregunta_1.jpg',
      parent: 'lectura_15',
    },
    {
      slug: 'pregunta_e',
      text: '¿Qué aprendió de su abuelita?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_15/pregunta_1.jpg',
      parent: 'lectura_15',
    },
    {
      slug: 'pregunta_a',
      text: '¿A qué país se le canta?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_16/pregunta_1.jpg',
      parent: 'lectura_16',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué se dice del Perú?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_16/pregunta_2.jpg',
      parent: 'lectura_16',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué siente el autor por su país?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_16/pregunta_3.jpg',
      parent: 'lectura_16',
    },
    {
      slug: 'pregunta_d',
      text: '¿Para qué se ha escrito el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_16/pregunta_3.jpg',
      parent: 'lectura_16',
    },
    {
      slug: 'pregunta_a',
      text: '¿Porque falta la lectura 17?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_17/pregunta_1.jpg',
      parent: 'lectura_17',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué es el cóndor?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_18/pregunta_1.jpg',
      parent: 'lectura_18',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué quiere decir que está en peligro de extinción?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_18/pregunta_2.jpg',
      parent: 'lectura_18',
    },
    {
      slug: 'pregunta_c',
      text: 'Según el texto: ¿Para qué cazan al Condor? ',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_18/pregunta_3.jpg',
      parent: 'lectura_18',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué texto has leído?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_19/pregunta_1.jpg',
      parent: 'lectura_19',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué ha pasado con el niño?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_19/pregunta_2.jpg',
      parent: 'lectura_19',
    },
    {
      slug: 'pregunta_c',
      text: '¿Por qué se dice que es ejemplo de perseverancia?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_19/pregunta_3.jpg',
      parent: 'lectura_19',
    },
    {
      slug: 'pregunta_d',
      text: '¿Cuál es el sueño del niño?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_19/pregunta_3.jpg',
      parent: 'lectura_19',
    },
    {
      slug: 'pregunta_a',
      text: 'Porque falta la pregunta 20',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_20/pregunta_1.jpg',
      parent: 'lectura_20',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué observas en la imagen?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_1/pregunta_1.jpg',
      parent: 'juego_1',
    },
    {
      slug: 'pregunta_b',
      text: '¿De qué crees que tratará el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_1/pregunta_1.jpg',
      parent: 'juego_1',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué tipo de texto será?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_1/pregunta_1.jpg',
      parent: 'juego_1',
    },
    {
      slug: 'pregunta_a',
      text: '¿Cuál sería el mejor título para el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_2/pregunta_1.jpg',
      parent: 'juego_2',
    },
    {
      slug: 'pregunta_b',
      text: '¿De qué crees que tratará el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_2/pregunta_1.jpg',
      parent: 'juego_2',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué crees que tratará el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_4/pregunta_1.jpg',
      parent: 'juego_4',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué estarán haciendo las personas de la imagen?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_5/pregunta_1.jpg',
      parent: 'juego_5',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué país estarán defendiendo? ',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_5/pregunta_2.jpg',
      parent: 'juego_5',
    },
    {
      slug: 'pregunta_a',
      text: '¿Cuál es la respuesta de la adivinanza?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_6/pregunta_1.jpg',
      parent: 'juego_6',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué conoces sobre los rios?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_6/pregunta_2.jpg',
      parent: 'juego_6',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué observas en las imágenes?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_7/pregunta_1.jpg',
      parent: 'juego_7',
    },
    {
      slug: 'pregunta_b',
      text: '¿A qué regiones pertenecen las danzas?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_7/pregunta_2.jpg',
      parent: 'juego_7',
    },
    {
      slug: 'pregunta_c',
      text: 'El huayno ¿A qué región pertenece?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_7/pregunta_3.jpg',
      parent: 'juego_7',
    },
    {
      slug: 'pregunta_a',
      text: '¿De quién es la silueta que completaste?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_8/pregunta_1.jpg',
      parent: 'juego_8',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué conoces sobre ella?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_8/pregunta_1.jpg',
      parent: 'juego_8',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué hay detrás de la silueta de esa persona? ',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_8/pregunta.jpg',
      parent: 'juego_8',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué crees que tratará el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_9/pregunta.jpg',
      parent: 'juego_9',
    },
    {
      slug: 'pregunta_a',
      text: '¿Cuál será el título del texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_10/pregunta.jpg',
      parent: 'juego_10',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué crees que tratará el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_11/pregunta.jpg',
      parent: 'juego_11',
    },
    {
      slug: 'pregunta_a',
      text: '.¿De que tratará el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_12/pregunta.jpg',
      parent: 'juego_12',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué tipo de texto será?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_12/pregunta.jpg',
      parent: 'juego_12',
    },
    {
      slug: 'pregunta_a',
      text: '¿De quién es la imagen?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_13/pregunta.jpg',
      parent: 'juego_13',
    },
    {
      slug: 'pregunta_b',
      text: '¿Cuáles son sus características?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_13/pregunta.jpg',
      parent: 'juego_13',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué objetos relacionaste?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_14/pregunta.jpg',
      parent: 'juego_14',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué necesitan estos electrodomésticos para funcionar?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_14/pregunta.jpg',
      parent: 'juego_14',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué frase formaste en el rompecabezas?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_15/pregunta.jpg',
      parent: 'juego_15',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué observas en la imagen?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_15/pregunta.jpg',
      parent: 'juego_15',
    },
    {
      slug: 'pregunta_c',
      text: '¿Qué conoces sobre el Señor de los Milagros?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_15/pregunta.jpg',
      parent: 'juego_15',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué frase dice en el rompecabezas que armaste?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_16/pregunta.jpg',
      parent: 'juego_16',
    },
    {
      slug: 'pregunta_b',
      text: '¿A qué se referirá la frase “¡Que empiece la jarana!”?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_16/pregunta.jpg',
      parent: 'juego_16',
    },
    {
      slug: 'pregunta_a',
      text: '¿No hay pregunta?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_17/pregunta.jpg',
      parent: 'juego_17',
    },
    {
      slug: 'pregunta_a',
      text: '¿De qué animal trata el texto?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_18/pregunta.jpg',
      parent: 'juego_18',
    },
    {
      slug: 'pregunta_b',
      text: '¿Qué está pasando con este animal?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_18/pregunta.jpg',
      parent: 'juego_18',
    },
    {
      slug: 'pregunta_a',
      text: '¿Qué está haciendo el niño?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_19/pregunta.jpg',
      parent: 'juego_19',
    },
    {
      slug: 'pregunta_b',
      text: '¿Por qué crees que estará escribiendo en la calle y de noche?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_19/pregunta.jpg',
      parent: 'juego_19',
    },
    {
      slug: 'pregunta_a',
      text: '¿No hay pregunta?',
      body: '',
      hint: '',
      type: 'multiple choice',
      image: 'lectura_20/pregunta.jpg',
      parent: 'juego_20',
    },
  ],
  multiforms: [
    {
      slug: 'lectura_1',
      minScore: 4,
    },
    {
      slug: 'lectura_2',
      minScore: 2,
    },
    {
      slug: 'lectura_3',
      minScore: 2,
    },
    {
      slug: 'lectura_4',
      minScore: 3,
    },
    {
      slug: 'lectura_5',
      minScore: 3,
    },
    {
      slug: 'lectura_6',
      minScore: 3,
    },
    {
      slug: 'lectura_7',
      minScore: 3,
    },
  ],
})

export const getters = {
  getQuestionsByParent: state => id => {
    if (!id) return []
    return state.questions.filter(question => {
      return question.parent === id
    })
  },
  getMultiform: state => slug => {
    return state.multiforms.find(multiform => {
      return multiform.slug === slug
    })
  },
}

export const mutations = {
  toggle(state, todo) {
    todo.done = !todo.done
  },
}
